data:
    # The name of the LTLA (Lower Tier Local Authority)
    # to draw data from. Change this to any valid LTLA.
    # Valid LTLA values for LOCAL_LOC can be found here:
    # https://data.gov.uk/dataset/adb48074-34f0-4304-8dc4-e294240ad630/lower-tier-local-authority-to-upper-tier-local-authority-december-2018-lookup-in-england-and-wales-v2

    # DEFAULTS:
    #local_loc: Exeter
    #local_loc_type: ltla
    local_loc: Exeter
    local_loc_type: utla
    # The name of the nation to draw data from.
    # Valid values are "England", "Northern Ireland", "Scotland"
    # and "Wales".

    # DEFAULTS:
    #nat_loc: England
    nat_loc: England
news:
    # The terms for which to filter news articles for the news display.
    # They are applied on an "inclusive OR" basis for each word,
    # meaning the default searches for articles containing the words
    # "covid", "covid-19" or "coronavirus".

    # DEFAULTS:
    #covid_terms: Covid COVID-19 coronavirus
    covid_terms: Covid COVID-19 coronavirus
    # The API key for the news api.
    # Get one here: https://newsapi.org/
    api_key: bbb44b41b5724f7d8cae5c7ce385df4d
logging:
    # The logging level, representing how much about execution is logged.

    # If set to "debug", logging will include debugging information.
    # If set to "info", logging will include runtime information.
    # If set to "warning", logging will include warning information.
    # If set to "error", logging will include only error information.

    # DEFAULT:
    #level: warning
    level: warning
    # The name of the log file.

    # DEFAULT:
    #filename: sys.log
    filename: sys.log
